---
- name: Install Blueman (Debian/Ubuntu)
  become: true
  apt:
    name: blueman
    state: present
  when: ansible_facts.distribution in ["Ubuntu", "Debian"]

- name: Install Blueman (Fedora)
  become: true
  dnf:
    name: blueman
    state: present
  when: ansible_facts.distribution == "Fedora"

