- name: Install ghostty in Debian/Ubuntu
  become: true
  apt:
    name: ghostty
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Enable ghostty COPR repository (Fedora)
  become: true
  community.general.copr:
    name: scottames/ghostty
    state: enabled
  when: ansible_facts.os_family == "RedHat"

- name: Install ghostty (Fedora)
  become: true
  dnf:
    name: ghostty
    state: present
  when: ansible_facts.os_family == "RedHat"
