- name: Install swayimg in Debian/Ubuntu
  become: true
  apt:
    name: swayimg
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install swayimg in Fedora
  become: true
  dnf:
    name: swayimg
    state: present
  when: ansible_facts.os_family == "RedHat"

