---
- name: Install nvim in Linux
  import_tasks: linux.yml
  when: ansible_facts.system == "Linux"

- name: Install pynvim on Ubuntu
  ansible.builtin.apt:
    name: python3-pynvim
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"

- name: Install pynvim on Fedora
  ansible.builtin.dnf:
    name: python3-neovim
    state: present
  become: true
  when: ansible_facts.distribution == "Fedora"

- name: Bootstrap lazy.nvim and install plugins
  shell: nvim --headless -c 'quitall'
  changed_when: false
  ignore_errors: true
