- name: Install choose via cargo-binstall in Linux (non-Arch)
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y choose"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/choose"
  when: ansible_facts.os_family in ["Debian", "RedHat"]


