---
- name: Install Elixir in Debian/Ubuntu
  become: true
  apt:
    name:
      - elixir
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install Elixir in Fedora
  become: true
  dnf:
    name:
      - elixir
    state: present
  when: ansible_facts.os_family == "RedHat"

