- name: Install gping in Debian/Ubuntu
  become: true
  apt:
    name: gping
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install gping in Fedora
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y gping"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/gping"
  when: ansible_facts.os_family == "RedHat"

