- name: Install vivid in Ubuntu
  become: true
  apt:
    deb: https://github.com/sharkdp/vivid/releases/download/v{{ vivid_version }}/vivid_{{ vivid_version }}_amd64.deb
  when: ansible_facts.distribution == "Ubuntu"

- name: Install vivid in Fedora
  shell: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-binstall -y vivid"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/vivid"
  when: ansible_facts.os_family == "RedHat"

