---
- name: Install wl-clipboard in Debian/Ubuntu
  become: true
  apt:
    name: wl-clipboard
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Install wl-clipboard in Fedora
  become: true
  dnf:
    name: wl-clipboard
    state: present
  when: ansible_facts.os_family == "RedHat"
