---
- name: Download zellij binary on Linux
  become: true
  unarchive:
    src: "https://github.com/zellij-org/zellij/releases/download/v{{ zellij_version }}/zellij-{{ ansible_facts.architecture }}-unknown-linux-musl.tar.gz"
    remote_src: true
    dest: /usr/local/bin
    mode: '0755'
  when: ansible_facts.system == "Linux"
